name: iṇstall php my workflow
on: workflow_dispatch
jobs: 
  job-install-php: 
    run-on: ubuntu-latest
    steps:  
     - name: Update apt repo
      run: sudo apt update
     - name: install php 
      run: sudo apt install php -y
     - name: php verion
      run: php --version
